'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class map

    '''<summary>
    '''litGold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litGold As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''frmInfomatin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmInfomatin As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hidMapX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMapX As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMapY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMapY As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidIsPlayingGame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsPlayingGame As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidShipID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidShipID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidAllowRestart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAllowRestart As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCharacterName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCharacterName As Global.System.Web.UI.WebControls.HiddenField
End Class
