'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class rank

    '''<summary>
    '''litRegisterOrProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRegisterOrProfile As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland7 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland8 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment6 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland6 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment5 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland5 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment4 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland4 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopInvestment0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopInvestment0 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopIsland0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopIsland0 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTopQuiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTopQuiz As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litUsersCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUsersCount As Global.System.Web.UI.WebControls.Literal
End Class
